# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit/
language: en-US
early_access: false
reviews:
  profile: assertive
  auto_review:
    drafts: true
chat:
  auto_reply: true
